
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class cadClientes extends javax.swing.JFrame {
    ConexaoBD conexao_cli = new ConexaoBD();
    MaskFormatter formataFone;

    String s="";
    public cadClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnnovo.setMnemonic(KeyEvent.VK_N);
	btnsalvar.setMnemonic(KeyEvent.VK_S);
	btnexcluir.setMnemonic(KeyEvent.VK_E);
        btnalterar.setMnemonic(KeyEvent.VK_A);
	btnfechar.setMnemonic(KeyEvent.VK_F);
        conexao_cli.conecta();
        conexao_cli.executaSql("select * from clientes");
        try
        {
            //posiciona no primeiro registro
            conexao_cli.resultset.first();
            //exibe todos os registros no campo de texto
            tfcodigo.setText(conexao_cli.resultset.getString("codigo"));
            tfnome.setText(conexao_cli.resultset.getString("nome"));
            tfendereco.setText(conexao_cli.resultset.getString("endereco"));
            tfnumero.setText(conexao_cli.resultset.getString("numero"));
            tfcomplemento.setText(conexao_cli.resultset.getString("complemento"));
            tfbairro.setText(conexao_cli.resultset.getString("bairro"));
            tfcidade.setText(conexao_cli.resultset.getString("cidade"));
            cboestado.setSelectedItem(conexao_cli.resultset.getString("estado"));
            tffone.setText(conexao_cli.resultset.getString("fone"));
            tfemail.setText(conexao_cli.resultset.getString("email"));
            s=(conexao_cli.resultset.getString("sexo"));
            if (s.equals("m"))
            {
                rdbm.setSelected(true);
            }
            else if (s.equals("f"))
            {
                rdbf.setSelected(true);
            }
                    
        }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnultimo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnnovo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        tfnome = new javax.swing.JTextField();
        btnalterar = new javax.swing.JButton();
        tfcomplemento = new javax.swing.JTextField();
        btnfechar = new javax.swing.JButton();
        tfbairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfendereco = new javax.swing.JTextField();
        btnproximo = new javax.swing.JButton();
        btnprimeiro = new javax.swing.JButton();
        btnanterior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfnumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfcidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        try
        {
            formataFone = new MaskFormatter ("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a mascara");
        }
        tffone = new JFormattedTextField (formataFone);
        tfemail = new javax.swing.JTextField();
        cboestado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        rdbm = new javax.swing.JRadioButton();
        rdbf = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnultimo.setText("->|");
        btnultimo.setToolTipText("ultimo");
        btnultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnultimoActionPerformed(evt);
            }
        });

        jLabel3.setText("endereço:");

        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        jLabel4.setText("Complemento : ");

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btnfechar.setText("Fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        jLabel5.setText("Bairro :");

        btnproximo.setText("->");
        btnproximo.setToolTipText("proximo");
        btnproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproximoActionPerformed(evt);
            }
        });

        btnprimeiro.setText("|<-");
        btnprimeiro.setToolTipText("primeiro");
        btnprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprimeiroActionPerformed(evt);
            }
        });

        btnanterior.setText("<-");
        btnanterior.setToolTipText("anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("nome :");

        jLabel6.setText("Numero: ");

        jLabel7.setText("Cidade :");

        jLabel8.setText("Estado :");

        jLabel9.setText("Fone :");

        jLabel10.setText("Email :");

        tffone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffoneActionPerformed(evt);
            }
        });

        cboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        jLabel11.setText("Sexo :");

        buttonGroup1.add(rdbm);
        rdbm.setText("Masculino");
        rdbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbmActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbf);
        rdbf.setText("Feminino");
        rdbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(btnnovo)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfnome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btnsalvar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnexcluir)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnalterar)
                                                .addGap(11, 11, 11)
                                                .addComponent(btnfechar))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tffone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 100, Short.MAX_VALUE)))
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfendereco)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfbairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(14, 14, 14)
                                        .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rdbf)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rdbm))))
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnprimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnanterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnproximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnultimo)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprimeiro)
                    .addComponent(btnanterior)
                    .addComponent(btnproximo)
                    .addComponent(btnultimo)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rdbm))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbf)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tffone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo)
                    .addComponent(btnsalvar)
                    .addComponent(btnexcluir)
                    .addComponent(btnalterar)
                    .addComponent(btnfechar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultimoActionPerformed
        try{
            conexao_cli.resultset.last();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnultimoActionPerformed

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnfecharActionPerformed

    private void btnproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproximoActionPerformed
        try{
            conexao_cli.resultset.next();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnproximoActionPerformed

    private void btnprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimeiroActionPerformed
        try{
            conexao_cli.resultset.first();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }

    }//GEN-LAST:event_btnprimeiroActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        try{
            conexao_cli.resultset.previous();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void tffoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffoneActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
       s="";
        tfcodigo.setText("");
            tfnome.setText("");
            tfendereco.setText("");
            tfnumero.setText("");
            tfcomplemento.setText("");
            tfbairro.setText("");
            tfcidade.setText("");
            cboestado.setSelectedItem(-1);
            tffone.setText("");
            tfemail.setText("");
            buttonGroup1.clearSelection();
            rdbm.setSelected(false);
            rdbf.setSelected(false);
            
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
       //validação para campo de texto preenchimento obrigatório
        if(tfcodigo.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"Código obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfcodigo.requestFocus();
                }
       else if(tfnome.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"nome obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfnome.requestFocus();
                }
       else if(tfendereco.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"endereço obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfendereco.requestFocus();
                }
        else if(!rdbm.isSelected()&&!rdbf.isSelected())
                {
             JOptionPane.showMessageDialog(null,"sexo obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                rdbm.requestFocus();
                }
         else if(tfnumero.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"numero obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfnumero.requestFocus();
                }
         else if(tfbairro.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"bairro obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfbairro.requestFocus();
                }
         else if(tfcidade.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"cidade obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfcidade.requestFocus();
                }
         else if(cboestado.getSelectedIndex() ==-1)
                {
             JOptionPane.showMessageDialog(null,"estado obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                cboestado.requestFocus();
                }
       else if(tffone.getText().equals("(  )    -    "))
                {
             JOptionPane.showMessageDialog(null,"fone obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tffone.requestFocus();
                }
       
        else if(tfemail.getText().equals(""))
                {
             JOptionPane.showMessageDialog(null,"email obrigatório","Alerta",JOptionPane.INFORMATION_MESSAGE);
                tfemail.requestFocus();
                }
      
        else
        {
        
        try
        {
            String sql = "insert into clientes (codigo, nome,sexo, endereco , numero, complemento,bairro,cidade,estado,fone,email) Values('"+tfcodigo.getText() +"' ,'" +tfnome.getText()+"','"+s+"','"+tfendereco.getText()+"' ,'"+tfnumero.getText()+"','"+tfcomplemento.getText()+"','"+tfbairro.getText()+"','"+tfcidade.getText()+"','"+cboestado.getSelectedItem()+"','"+tffone.getText()+"','"+tfemail.getText()+"')";
            //executa sql,para atualização do banco usar o executeUpdate
            conexao_cli.statement.executeUpdate(sql);
             JOptionPane.showMessageDialog(null,"Dados gravados com sucesso"); 
             //atualiza resultset,para apenas consulta(comando select) utilizar o metodo executasql
             conexao_cli.executaSql("select * from clientes");
             conexao_cli.resultset.last();
             //chama o metodo mostraRegistro, que exibe o registro do banco no cambo texto
        }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro ao salvar"+ erro);     
        }
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
       try
       {
        String msg = "Excluir cliente " + tfnome.getText() + "?";
        int  opçao = JOptionPane.showConfirmDialog(null, msg, "Atenção", JOptionPane.YES_NO_OPTION);
        //caso opção igual a sim
        if (opçao == JOptionPane.YES_OPTION)
        {
            String sql = "delete from clientes where codigo = " + tfcodigo.getText();
            conexao_cli.statement.executeUpdate(sql);
            //atualiza resultset
            conexao_cli.executaSql("select * from clientes ");
            //posiciona no primeiro registro
            conexao_cli.resultset.first();
            //chama metodo que exibe registro no campo de texto
            mostraRegistro();
        }
        
       }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro ao excluir"+ erro);     
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
       try
       {
       
            String sql = "update clientes set nome = '" + tfnome.getText()+"', sexo = '" + s+"', endereco = '" + tfendereco.getText()+"' , numero = '" +tfnumero.getText()+"', complemento = '"+tfcomplemento.getText()+"', bairro = '"+tfbairro.getText()+"', cidade = '"+tfcidade.getText()+"', estado = '"+cboestado.getSelectedItem()+"', fone = '"+tffone.getText()+"', email = '"+tfemail.getText()+"'where codigo = "+tfcodigo.getText();
            conexao_cli.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"alteração realizada com sucesso");
            //atualiza resultset chama o metodo executasql
            conexao_cli.executaSql("select * from clientes ");
            //posiciona no ultimo registro
            conexao_cli.resultset.last();
            //chama metodo que exibe registro no campo de texto
            mostraRegistro();
        
        
       }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro ao alterar"+ erro);     
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void rdbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbmActionPerformed
        s="m";
    }//GEN-LAST:event_rdbmActionPerformed

    private void rdbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbfActionPerformed
        s="f";
    }//GEN-LAST:event_rdbfActionPerformed
 public void mostraRegistro(){
     try{
            rdbm.setSelected(false);
            rdbf.setSelected(false);
            s="";
            tfcodigo.setText(conexao_cli.resultset.getString("codigo"));
            tfnome.setText(conexao_cli.resultset.getString("nome"));
            tfendereco.setText(conexao_cli.resultset.getString("endereco"));
            tfnumero.setText(conexao_cli.resultset.getString("numero"));
            tfcomplemento.setText(conexao_cli.resultset.getString("complemento"));
            tfbairro.setText(conexao_cli.resultset.getString("bairro"));
            tfcidade.setText(conexao_cli.resultset.getString("cidade"));
            cboestado.setSelectedItem(conexao_cli.resultset.getString("estado"));
            tffone.setText(conexao_cli.resultset.getString("fone"));
            tfemail.setText(conexao_cli.resultset.getString("email"));
            s=(conexao_cli.resultset.getString("sexo"));
            if (s.equals("m"))
            {
                rdbm.setSelected(true);
            }
            else if (s.equals("f"))
            {
                rdbf.setSelected(true);
            }
     
 }
     catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadClientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnfechar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnprimeiro;
    private javax.swing.JButton btnproximo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnultimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdbf;
    private javax.swing.JRadioButton rdbm;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JTextField tfcidade;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfcomplemento;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfendereco;
    private javax.swing.JTextField tffone;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfnumero;
    // End of variables declaration//GEN-END:variables
}
