
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class cadCategorias extends javax.swing.JFrame {

    
      ConexaoBD conexao_cat = new ConexaoBD();
    /**
     * Creates new form cadCategorias
     */
    public cadCategorias() {
        
          
        initComponents();
        btnnovo.setMnemonic(KeyEvent.VK_N);
	btnsalvar.setMnemonic(KeyEvent.VK_S);
	btnexcluir.setMnemonic(KeyEvent.VK_E);
        btnalterar.setMnemonic(KeyEvent.VK_A);
	btnfechar.setMnemonic(KeyEvent.VK_F);
        conexao_cat.conecta();
        conexao_cat.executaSql("select * from categoria");
         try
        {
            //posiciona no primeiro registro
            conexao_cat.resultset.first();
            //exibe todos os registros no campo de texto
            tfcodigo.setText(conexao_cat.resultset.getString("codigo"));
            tfnome.setText(conexao_cat.resultset.getString("nome"));
            
        }
         catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfcodigo = new javax.swing.JTextField();
        btnanterior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnproximo = new javax.swing.JButton();
        btnprimeiro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnultimo = new javax.swing.JButton();
        tfnome = new javax.swing.JTextField();
        btnfechar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnanterior.setText("<-");
        btnanterior.setToolTipText("anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        btnproximo.setText("->");
        btnproximo.setToolTipText("proximo");
        btnproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproximoActionPerformed(evt);
            }
        });

        btnprimeiro.setText("|<-");
        btnprimeiro.setToolTipText("primeiro");
        btnprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprimeiroActionPerformed(evt);
            }
        });

        jLabel2.setText("nome :");

        btnultimo.setText("->|");
        btnultimo.setToolTipText("ultimo");
        btnultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnultimoActionPerformed(evt);
            }
        });

        btnfechar.setText("Fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnnovo)
                .addGap(18, 18, 18)
                .addComponent(btnsalvar)
                .addGap(18, 18, 18)
                .addComponent(btnexcluir)
                .addGap(18, 18, 18)
                .addComponent(btnalterar)
                .addGap(11, 11, 11)
                .addComponent(btnfechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnprimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnanterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnproximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnultimo)
                        .addGap(18, 18, 18))
                    .addComponent(tfnome, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprimeiro)
                    .addComponent(btnanterior)
                    .addComponent(btnproximo)
                    .addComponent(btnultimo)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo)
                    .addComponent(btnsalvar)
                    .addComponent(btnexcluir)
                    .addComponent(btnalterar)
                    .addComponent(btnfechar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        try{
            conexao_cat.resultset.previous();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproximoActionPerformed
        try{
            conexao_cat.resultset.next();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnproximoActionPerformed

    private void btnprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimeiroActionPerformed
        try{
            conexao_cat.resultset.first();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnprimeiroActionPerformed

    private void btnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultimoActionPerformed
        try{
            conexao_cat.resultset.last();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnultimoActionPerformed

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnfecharActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        try
        {
            String msg = "Excluir categoria " + tfnome.getText() + "?";
            int  opçao = JOptionPane.showConfirmDialog(null, msg, "Atenção", JOptionPane.YES_NO_OPTION);
            //caso opção igual a sim
            if (opçao == JOptionPane.YES_OPTION)
            {
                String sql = "delete from categoria where codigo = " + tfcodigo.getText();
                conexao_cat.statement.executeUpdate(sql);
                //atualiza resultset
                conexao_cat.executaSql("select * from categoria ");
                //posiciona no primeiro registro
                conexao_cat.resultset.first();
                //chama metodo que exibe registro no campo de texto
                mostraRegistro();
            }

        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"erro ao excluir"+ erro);
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try
        {
            String sql = "insert into categoria (codigo, nome) Values('"+tfcodigo.getText() +"' ,'" +tfnome.getText()+"')";
            //executa sql,para atualização do banco usar o executeUpdate
            conexao_cat.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Dados gravados com sucesso");
            //atualiza resultset,para apenas consulta(comando select) utilizar o metodo executasql
            conexao_cat.executaSql("select * from categoria");
            conexao_cat.resultset.last();
            //chama o metodo mostraRegistro, que exibe o registro do banco no cambo texto
        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"erro ao salvar"+ erro);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        
        tfcodigo.setText("");
        tfnome.setText("");
        

    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        try
        {

            String sql = "update categoria set nome = '" + tfnome.getText()+"'where codigo = "+tfcodigo.getText();
            conexao_cat.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"alteração realizada com sucesso");
            //atualiza resultset chama o metodo executasql
            conexao_cat.executaSql("select * from categoria ");
            //posiciona no ultimo registro
            conexao_cat.resultset.last();
            //chama metodo que exibe registro no campo de texto
            mostraRegistro();

        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"erro ao alterar"+ erro);
        }
    }//GEN-LAST:event_btnalterarActionPerformed
public void mostraRegistro(){
     try{
            
            tfcodigo.setText(conexao_cat.resultset.getString("codigo"));
            tfnome.setText(conexao_cat.resultset.getString("nome"));
            
 }
      catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadCategorias().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnfechar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnprimeiro;
    private javax.swing.JButton btnproximo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfnome;
    // End of variables declaration//GEN-END:variables
}
