
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class cadFuncionarios extends javax.swing.JFrame {
 ConexaoBD conexao_fun = new ConexaoBD();
 //cria objeto para mascara de entrada
 MaskFormatter formataFone, formataCpf, formataCelular, formataCep;
    
    public cadFuncionarios() {
        initComponents();
         this.setLocationRelativeTo(null);
        btnnovo.setMnemonic(KeyEvent.VK_N);
	btnsalvar.setMnemonic(KeyEvent.VK_S);
	btnexcluir.setMnemonic(KeyEvent.VK_E);
        btnalterar.setMnemonic(KeyEvent.VK_A);
	btnfechar.setMnemonic(KeyEvent.VK_F);
        conexao_fun.conecta();
        conexao_fun.executaSql("select * from funcionarios");
        try
        {
            //posiciona no primeiro registro
            conexao_fun.resultset.first();
            //exibe todos os registros no campo de texto
            tfcodigo.setText(conexao_fun.resultset.getString("codigo"));
            tfnome.setText(conexao_fun.resultset.getString("nome"));
            tfendereco.setText(conexao_fun.resultset.getString("endereco"));
            tfnumero.setText(conexao_fun.resultset.getString("numero"));
            tfcomplemento.setText(conexao_fun.resultset.getString("complemento"));
            tfbairro.setText(conexao_fun.resultset.getString("bairro"));
            tfcidade.setText(conexao_fun.resultset.getString("cidade"));
            cboestado.setSelectedItem(conexao_fun.resultset.getString("estado"));
            tffone.setText(conexao_fun.resultset.getString("foneResid"));
            tfemail.setText(conexao_fun.resultset.getString("email"));
             tfcpf.setText(conexao_fun.resultset.getString("cpf"));
            tfcep.setText(conexao_fun.resultset.getString("cep"));
            tfcelular.setText(conexao_fun.resultset.getString("celular"));
           
                    
        }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfcodigo = new javax.swing.JTextField();
        btnanterior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnproximo = new javax.swing.JButton();
        btnprimeiro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfendereco = new javax.swing.JTextField();
        btnfechar = new javax.swing.JButton();
        tfbairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfnumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfcidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnultimo = new javax.swing.JButton();
        tfcomplemento = new javax.swing.JTextField();
        cboestado = new javax.swing.JComboBox();
        btnexcluir = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnnovo = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        tfnome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        try
        {
            formataCpf = new MaskFormatter ("###.###.###-##");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a mascara");
        }
        tfcpf = new JFormattedTextField(formataCpf);
        try
        {
            formataCep = new MaskFormatter ("#####-###");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a mascara");
        }
        tfcep = new JFormattedTextField(formataCep);
        try
        {
            formataFone = new MaskFormatter ("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a mascara");
        }
        tffone = new JFormattedTextField(formataFone);
        try
        {
            formataCelular = new MaskFormatter ("(##)#####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a mascara");
        }
        tfcelular = new JFormattedTextField(formataCelular);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnanterior.setText("<-");
        btnanterior.setToolTipText("anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        btnproximo.setText("->");
        btnproximo.setToolTipText("proximo");
        btnproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproximoActionPerformed(evt);
            }
        });

        btnprimeiro.setText("|<-");
        btnprimeiro.setToolTipText("primeiro");
        btnprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprimeiroActionPerformed(evt);
            }
        });

        jLabel5.setText("Bairro :");

        btnfechar.setText("Fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero: ");

        jLabel2.setText("nome :");

        jLabel7.setText("Cidade :");

        jLabel8.setText("Estado :");

        jLabel9.setText("Fone :");

        jLabel10.setText("Email :");

        jLabel3.setText("endereço:");

        btnultimo.setText("->|");
        btnultimo.setToolTipText("ultimo");
        btnultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnultimoActionPerformed(evt);
            }
        });

        cboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        jLabel4.setText("Complemento : ");

        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        jLabel11.setText("cpf :");

        jLabel12.setText("CEP:");

        jLabel13.setText("Celular: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(btnnovo)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfendereco)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfbairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)))
                                .addComponent(jLabel8)
                                .addGap(14, 14, 14)
                                .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnsalvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnexcluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnalterar)
                                        .addGap(11, 11, 11)
                                        .addComponent(btnfechar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(tfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tffone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(tfcep, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 239, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnanterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnproximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnultimo)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfnome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprimeiro)
                    .addComponent(btnanterior)
                    .addComponent(btnproximo)
                    .addComponent(btnultimo)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(tffone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo)
                    .addComponent(btnsalvar)
                    .addComponent(btnexcluir)
                    .addComponent(btnalterar)
                    .addComponent(btnfechar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        try{
            conexao_fun.resultset.previous();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproximoActionPerformed
        try{
            conexao_fun.resultset.next();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnproximoActionPerformed

    private void btnprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimeiroActionPerformed
        try{
            conexao_fun.resultset.first();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnprimeiroActionPerformed

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnfecharActionPerformed

    private void btnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultimoActionPerformed
        try{
            conexao_fun.resultset.last();
            mostraRegistro();
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);
        }
    }//GEN-LAST:event_btnultimoActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        try
        {
            String msg = "Excluir funcionario " + tfnome.getText() + "?";
            int  opçao = JOptionPane.showConfirmDialog(null, msg, "Atenção", JOptionPane.YES_NO_OPTION);
            //caso opção igual a sim
            if (opçao == JOptionPane.YES_OPTION)
            {
                String sql = "delete from funcionarios where codigo = " + tfcodigo.getText();
               conexao_fun.statement.executeUpdate(sql);
                //atualiza resultset
                conexao_fun.executaSql("select * from funcionarios ");
                //posiciona no primeiro registro
                conexao_fun.resultset.first();
                //chama metodo que exibe registro no campo de texto
                mostraRegistro();
            }

        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"erro ao excluir"+ erro);
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try
        {
            String sql = "insert into funcionarios (codigo, nome, endereco , numero, complemento,bairro,cidade,estado,foneResid,email,cep,cpf,celular) Values('"+tfcodigo.getText() +"' ,'" +tfnome.getText()+"','"+tfendereco.getText()+"' ,'"+tfnumero.getText()+"','"+tfcomplemento.getText()+"','"+tfbairro.getText()+"','"+tfcidade.getText()+"','"+cboestado.getSelectedItem()+"','"+tffone.getText()+"','"+tfemail.getText()+"','"+tfcep.getText()+"','"+tfcpf.getText()+"','"+tfcelular.getText()+"')";
            //executa sql,para atualização do banco usar o executeUpdate
            conexao_fun.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Dados gravados com sucesso");
            //atualiza resultset,para apenas consulta(comando select) utilizar o metodo executasql
            conexao_fun.executaSql("select * from funcionarios");
            conexao_fun.resultset.last();
            //chama o metodo mostraRegistro, que exibe o registro do banco no cambo texto
        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"erro ao salvar"+ erro);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        
        tfcodigo.setText("");
        tfnome.setText("");
        tfendereco.setText("");
        tfnumero.setText("");
        tfcomplemento.setText("");
        tfbairro.setText("");
        tfcidade.setText("");
        cboestado.setSelectedItem(-1);
        tffone.setText("");
        tfemail.setText("");
        tfcpf.setText("");
        tfcep.setText("");
        tfcelular.setText("");

    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        try
        {

            String sql = "update funcionarios set nome = '" + tfnome.getText()+"', endereco = '" + tfendereco.getText()+"' , numero = '" +tfnumero.getText()+"', complemento = '"+tfcomplemento.getText()+"', bairro = '"+tfbairro.getText()+"', cidade = '"+tfcidade.getText()+"', estado = '"+cboestado.getSelectedItem()+"', foneResid = '"+tffone.getText()+"', celular = '"+tfcelular.getText()+"', cpf = '"+tfcpf.getText()+"', cep = '"+tfcep.getText()+"', email = '"+tfemail.getText()+"'where codigo = "+tfcodigo.getText();
            conexao_fun.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"alteração realizada com sucesso");
            //atualiza resultset chama o metodo executasql
            conexao_fun.executaSql("select * from funcionarios ");
            //posiciona no ultimo registro
            conexao_fun.resultset.last();
            //chama metodo que exibe registro no campo de texto
            mostraRegistro();

        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"erro ao alterar"+ erro);
        }
    }//GEN-LAST:event_btnalterarActionPerformed
 public void mostraRegistro(){
try
        {
           
            
            //exibe todos os registros no campo de texto
            tfcodigo.setText(conexao_fun.resultset.getString("codigo"));
            tfnome.setText(conexao_fun.resultset.getString("nome"));
            tfendereco.setText(conexao_fun.resultset.getString("endereco"));
            tfnumero.setText(conexao_fun.resultset.getString("numero"));
            tfcomplemento.setText(conexao_fun.resultset.getString("complemento"));
            tfbairro.setText(conexao_fun.resultset.getString("bairro"));
            tfcidade.setText(conexao_fun.resultset.getString("cidade"));
            cboestado.setSelectedItem(conexao_fun.resultset.getString("estado"));
            tffone.setText(conexao_fun.resultset.getString("foneResid"));
            tfemail.setText(conexao_fun.resultset.getString("email"));
             tfcpf.setText(conexao_fun.resultset.getString("cpf"));
            tfcep.setText(conexao_fun.resultset.getString("cep"));
            tfcelular.setText(conexao_fun.resultset.getString("celular"));
           
                    
        }
 

        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
        }
 }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadFuncionarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnfechar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnprimeiro;
    private javax.swing.JButton btnproximo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnultimo;
    private javax.swing.JComboBox cboestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JFormattedTextField tfcelular;
    private javax.swing.JFormattedTextField tfcep;
    private javax.swing.JTextField tfcidade;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfcomplemento;
    private javax.swing.JFormattedTextField tfcpf;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfendereco;
    private javax.swing.JFormattedTextField tffone;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfnumero;
    // End of variables declaration//GEN-END:variables
}
