
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class cadProdutos extends javax.swing.JFrame {
    ConexaoBD conexao_prod = new ConexaoBD();
    ConexaoBD conexao_cat = new ConexaoBD();
    boolean primeiravezcategoria = true;
    String codCategoria,nomeCategoria;

    /**
     * Creates new form cadProdutos
     */
    public cadProdutos() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnnovo.setMnemonic(KeyEvent.VK_N);
	btnsalvar.setMnemonic(KeyEvent.VK_S);
	btnexcluir.setMnemonic(KeyEvent.VK_E);
        btnalterar.setMnemonic(KeyEvent.VK_A);
	btnfechar.setMnemonic(KeyEvent.VK_F);
        conexao_prod.conecta();
        conexao_cat.conecta();
        conexao_cat.executaSql("select * from categoria order by nome");
        conexao_prod.executaSql("select * from produtos");
        try
        {
            //comando para carregar categoria na cbo,enquanto houver proximo registro ele add na cbo
            while (conexao_cat.resultset.next())
            {
               cbocategoria.addItem(conexao_cat.resultset.getString("nome"));
            }
            //posiciona no primeiro registro
            conexao_prod.resultset.first();
            //exibe todos os registros no campo de texto
            tfcodigo.setText(conexao_prod.resultset.getString("codigo"));
            tfnome.setText(conexao_prod.resultset.getString("nome"));
            tfprecocusto.setText(conexao_prod.resultset.getString("precocusto"));
            tfprecovenda.setText(conexao_prod.resultset.getString("precovenda"));
            tfestoque.setText(conexao_prod.resultset.getString("estoque"));
            tfcodcategoria.setText(conexao_prod.resultset.getString("cadCategoria"));
            buscaCategoria();
                    
        }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro na conexao com o SQL mmm "+ erro);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfprecocusto = new javax.swing.JTextField();
        tfprecovenda = new javax.swing.JTextField();
        tfestoque = new javax.swing.JTextField();
        btnprimeiro = new javax.swing.JButton();
        btnanterior = new javax.swing.JButton();
        btnproximo = new javax.swing.JButton();
        btnultimo = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btnfechar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbocategoria = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tfcodcategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel1.setText("Código:");

        jLabel2.setText("nome :");

        jLabel3.setText("Preço de Custo:");

        jLabel4.setText("Preço de venda :");

        jLabel5.setText("Estoque :");

        btnprimeiro.setText("|<-");
        btnprimeiro.setToolTipText("primeiro");
        btnprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprimeiroActionPerformed(evt);
            }
        });

        btnanterior.setText("<-");
        btnanterior.setToolTipText("anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });

        btnproximo.setText("->");
        btnproximo.setToolTipText("proximo");
        btnproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproximoActionPerformed(evt);
            }
        });

        btnultimo.setText("->|");
        btnultimo.setToolTipText("ultimo");
        btnultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnultimoActionPerformed(evt);
            }
        });

        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btnfechar.setText("Fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        jLabel6.setText("Categoria:");

        cbocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocategoriaActionPerformed(evt);
            }
        });

        jLabel7.setText("Cod categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 132, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnprimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnanterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnproximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnultimo)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(btnnovo)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnexcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnalterar)
                                .addGap(11, 11, 11)
                                .addComponent(btnfechar))
                            .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfestoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(tfprecovenda, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfprecocusto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfcodcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprimeiro)
                            .addComponent(btnanterior)
                            .addComponent(btnproximo)
                            .addComponent(btnultimo)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfprecocusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cbocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfprecovenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfcodcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo)
                    .addComponent(btnsalvar)
                    .addComponent(btnexcluir)
                    .addComponent(btnalterar)
                    .addComponent(btnfechar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnfecharActionPerformed

    private void btnprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimeiroActionPerformed
      try{
        conexao_prod.resultset.first();
        mostraRegistro();
      }
      catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
      
    }//GEN-LAST:event_btnprimeiroActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
       try{
        conexao_prod.resultset.previous();
        mostraRegistro();
      }
      catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproximoActionPerformed
       try{
        conexao_prod.resultset.next();
        mostraRegistro();
      }
      catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
    }//GEN-LAST:event_btnproximoActionPerformed

    private void btnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultimoActionPerformed
        try{
        conexao_prod.resultset.last();
        mostraRegistro();
      }
      catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
    }//GEN-LAST:event_btnultimoActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
            tfcodigo.setText("");
            tfnome.setText("");
            tfprecocusto.setText("");
            tfprecovenda.setText("");
            tfestoque.setText("");
            cbocategoria.setSelectedItem(-1);
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
      
        try
        {
            String sql = "insert into produtos (codigo, nome, precocusto , precovenda, estoque,cadCategoria) Values('"+tfcodigo.getText() +"' ,'" +tfnome.getText()+"','"+tfprecocusto.getText()+"' ,'"+tfprecovenda.getText()+"','"+tfestoque.getText()+"','"+cbocategoria.getSelectedItem()+"')";
            //executa sql,para atualização do banco usar o executeUpdate
            conexao_prod.statement.executeUpdate(sql);
             JOptionPane.showMessageDialog(null,"Dados gravados com sucesso"); 
             //atualiza resultset,para apenas consulta(comando select) utilizar o metodo executasql
             conexao_prod.executaSql("select * from produtos");
             conexao_prod.resultset.last();
             //chama o metodo mostraRegistro, que exibe o registro do banco no cambo texto
        }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro ao salvar"+ erro);     
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
       try
       {
        String msg = "Excluir produto " + tfnome.getText() + "?";
        int  opçao = JOptionPane.showConfirmDialog(null, msg, "Atenção", JOptionPane.YES_NO_OPTION);
        //caso opção igual a sim
        if (opçao == JOptionPane.YES_OPTION)
        {
            String sql = "delete from produtos where codigo = " + tfcodigo.getText();
            //atualiza resultset
            conexao_prod.executaSql("select * from produtos ");
            //posiciona no primeiro registro
            conexao_prod.resultset.first();
            //chama metodo que exibe registro no campo de texto
            mostraRegistro();
        }
        
       }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro ao excluir"+ erro);     
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        try
       {
       
            String sql = "update produtos set nome = '" + tfnome.getText()+"',precocusto = '" + tfprecocusto.getText()+"' , precovenda = '" +tfprecovenda.getText()+"', estoque = '"+tfestoque.getText()+"' , cadCategoria = '"+tfcodcategoria.getText() + "' where codigo = "+tfcodigo.getText();
            conexao_prod.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"alteração realizada com sucesso");
            //atualiza resultset chama o metodo executasql
            conexao_prod.executaSql("select * from produtos ");
            //posiciona no ultimo registro
            conexao_prod.resultset.last();
            //chama metodo que exibe registro no campo de texto
            mostraRegistro();
        
        
       }
        catch (SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro ao alterar"+ erro);     
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void cbocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocategoriaActionPerformed
if (primeiravezcategoria==false)
    //variavel utilizada para que o bloco de comando abaixo NAO seja executado assim que o form for exibido pela primeira vez 
      {

        try {
            String sql = " select * from categoria where nome like'"+cbocategoria.getSelectedItem()+"'";
            conexao_cat.executaSql(sql);
            //posiciona no primeiro registro encontrado, do resultado da consulta sql
            conexao_cat.resultset.first();
            //add o codigo da categoria no campo de texto
            tfcodcategoria.setText(conexao_cat.resultset.getString("codigo"));
            
            
        }
        catch(SQLException erro)
        {
          JOptionPane.showMessageDialog(null,"erro : "+ erro);  
        }
      }
      primeiravezcategoria =false;
    }//GEN-LAST:event_cbocategoriaActionPerformed
 public void mostraRegistro(){
     try{
     tfcodigo.setText(conexao_prod.resultset.getString("codigo"));
            tfnome.setText(conexao_prod.resultset.getString("nome"));
            tfprecocusto.setText(conexao_prod.resultset.getString("precocusto"));
            tfprecovenda.setText(conexao_prod.resultset.getString("precovenda"));
            tfestoque.setText(conexao_prod.resultset.getString("estoque"));
            tfcodcategoria.setText(conexao_prod.resultset.getString("cadCategoria"));
            buscaCategoria();
 }
     catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"erro na conexao com o SQL"+ erro);  
     }
 }
 public void buscaCategoria(){
     try{
         
     
     codCategoria = tfcodcategoria.getText();
     String sql = "select nome from categoria where codigo like'"  +codCategoria +"'";
     conexao_cat.executaSql(sql);
     conexao_cat.resultset.first();
     cbocategoria.setSelectedItem(conexao_cat.resultset.getString("nome"));
             }
     
     catch (SQLException erro)
     {
         JOptionPane.showMessageDialog(null,"erro busca Categoria"+ erro); 
     }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadProdutos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnfechar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnprimeiro;
    private javax.swing.JButton btnproximo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnultimo;
    private javax.swing.JComboBox cbocategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfcodcategoria;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfestoque;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfprecocusto;
    private javax.swing.JTextField tfprecovenda;
    // End of variables declaration//GEN-END:variables
}
